### PR TITLE
Square dalitz eff pdf

### PR DESCRIPTION
**Pull request by marthaisabelhilton**
Dear GooFit experts,
I am trying to add this SquareDalitzEffPdf to GooFit and I'm wondering if you can help me.
When trying to build I am getting the following error:
```
/hepgpu5-data1/mhilton/GooFit/include/goofit/PdfBase.h(139): error: no instance of overloaded function "filter_arguments" matches the argument list
            argument types are: (std::vector<GooFit::Observable, std::allocator<GooFit::Observable>>, std::vector<GooFit::Variable, std::allocator<GooFit::Variable>>, std::vector<GooFit::Observable, std::allocator<GooFit::Observable>>, std::vector<GooFit::Variable, std::allocator<GooFit::Variable>>)
          detected during instantiation of "GooFit::PdfBase::PdfBase(std::__cxx11::string, std::__cxx11::string, Args...) [with Args=<std::vector<GooFit::Observable, std::allocator<GooFit::Observable>>, std::vector<GooFit::Variable, std::allocator<GooFit::Variable>>>]"
```
Please can you take a look at what might be wrong?
Many thanks.

### CODE REVIEW

**Comment by marthaisabelhilton** [comment]
Hi @henryiii I've implemented a (not very elegant) fix so this seems to work now.

**Comment by marthaisabelhilton** [comment]
Hi please would somebody be able to have a look at this?
I am getting some errors when trying to use this Pdf with my Amp3Body.
`terminate called after throwing an instance of 'thrust::system::system_error'
  what():  function_attributes(): after cudaFuncGetAttributes: operation not supported on global/shared address space
Aborted`
Do you know what might be wrong?

**Comment by marthaisabelhilton** [comment]
To provide some more information I see this is happening somewhere after line 244 in Amp3Body.cu in the normalize function. Also when I try to normalize the SquareDalitzEffPdf I get Non-positive normalization. I'm not sure why...

**Comment by marthaisabelhilton** [comment]
Hi I can provide a minimal working example of where I am trying to use this Pdf.
[SquareDalitzEffPdf_test.py.txt](https://github.com/GooFit/GooFit/files/3636546/SquareDalitzEffPdf_test.py.txt)

**Comment by henryiii** [comment]
Okay, I'll try to take a look at it. Sorry for the delay!

**Comment by marthaisabelhilton** [comment]
Hi @henryiii do you have any update on this? Many thanks.

**Comment by marthaisabelhilton** [comment]
Hi I have some more information about this which might help. I've been trying to add generic pdfs as the efficiency to Amp3Body ie. PolynomialPdf and SmoothHistogramPdf. A zeroth order PolynomialPdf works, anything else gives the following error:
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  function_attributes(): after cudaFuncGetAttributes: operation not supported on global/shared address space
Aborted
Maybe this can help with the problem?
Many thanks.

**Pull request merged**
