### PR TITLE
Added getName to Variable python binding.

### PR DESCRIPTION
**Pull request by marthaisabelhilton**

### CODE REVIEW

**Comment by henryiii** [comment]
Just curious, why not use the name property defined in the line below? `v.name` instead of `v.GetName()`?

**Comment by henryiii** [comment]
By the way, there's a macro that adds both forms, I think we should use that.

**Comment by marthaisabelhilton** [comment]
I don't think you can use ```name``` in python as it is a built in function?

**Comment by henryiii** [comment]
Nope, `name` is not a built in. `__name__` is sort-of a built-in, at least it is defined in most contexts. However, even if it was a built-in, it's perfectly valid to overwrite builtins, especially as methods. You just can't overwrite keywords, like `if`.

**Pull request merged**
