### PR TITLE
WIP: New indexing

### PR DESCRIPTION
**Pull request by henryiii**
This is an initial merge of the indexing branch #91 . Many things are broken, especially in regards to variables in PDFs. The diff on GitHub should help guide the cleanup. Changes:
* `GetObservableIndex` -> `GetIndex`, since I think the regular index is not used. It might be removable from `Variable`s?

### CODE REVIEW

**Comment by henryiii** [comment]
@galapaegos can I merge the latest changes in master in?

**Comment by galapaegos** [comment]
@henryiii, Into this branch?  That sounds good.  I'm attempting to write up a HOWTO for creating PDFs with the new format.

**Comment by henryiii** [comment]
I've fixed a few things, and updated the style. So far, at least locally, I see the following issues:
* Six failing tests
* The binned test fails; it's converging but finding a totally different result for alpha (simple exponential distribution with alpha = -1.5). This makes me think there might be an issue with binned datasets.
* Switching to Minuit2 causes more tests to fail, the two methods should be mostly identical, and Minuit2 should be the default (doesn't require ROOT). I've added one location where the fit manager can be changed for many of the tests.

**Comment by henryiii** [comment]
Fixed a problem due wrong expected integral of exppdf in master (un-copied parameters).

**Comment by henryiii** [comment]
Congratulations! I'll check it over and merge soon.

**Comment by galapaegos** [comment]
@henryiii Thanks!

I am working to fix DP4/SigGen/Tddp4 next.

**Comment by henryiii** [comment]
I've sped up and cleaned up Travis, now only builds on PRs instead of branch + PR. Let me know when you are ready to merge. I'll sync the current 2.1 branch to master, then we can backport any critical fixes to that branch if needed.

**Pull request merged**
