### PR TITLE
Add kMatrix to Python bindings

### PR DESCRIPTION
**Pull request by marthaisabelhilton**
Dear @henryiii and GooFit experts,
I am trying to add the kMatrix lineshape to the python bindings but it is not working. I was wondering if you could take a look to see if there is something wrong?
Many thanks.

### CODE REVIEW

**Comment by marthaisabelhilton** [comment]
Hi @henryiii and others,
Is anyone able to have a look at this?
Sorry to bother you and many thanks for your help.

**Comment by henryiii** [comment]
Sorry, I and my family have been sick this weekend. Will be getting back to work today.

**Comment by henryiii** [comment]
I've simplified the history and applied the formatting, will address the actual problem next (computer is updating Xcode so can't build at the moment).

**Comment by henryiii** [comment]
I've changed the input to vector, then just check the size to make sure it is the correct size for f_scatter and matrix of poles - you can't default-construct an std::array, and it's not supported by default in pybind11 anyway.

**Comment by henryiii** [comment]
Keep in mind, kMatix is experimental, and hasn't been throughly validated. It also is off by default on CUDA builds due to the amount of time it takes to compile.

**Pull request merged**
