### PR TITLE
Fixing spline

### PR DESCRIPTION
**Pull request by henryiii**
@galapaegos, can you take a look? This doesn't work (trying to recover code which seems to have been commented out in GooFit 2.2.0).

@JuanBSLeite has code here that runs it: https://github.com/JuanBSLeite/goofit_charm - we could turn it into a test or an example. Or both.

```bash
cd goofit_charm
./D2PPP gen
open plots/PDF.png
```

### CODE REVIEW

**Comment by galapaegos** [comment]
@henryiii, @JuanBSLeite 

I'm getting some errors about a missing file 'files/DsPPP_TIS_PosTS_par_sPloted_large__MVA.root'. Can this file be provided under goofit_charm or another means?  Thanks!

**Comment by henryiii** [comment]
I was able to run with no extra files. Are you changing to the subdirectory after building and before running?

**Comment by JuanBSLeite** [comment]
@galapaegos @henryiii 
I'll fix it.

**Comment by JuanBSLeite** [comment]
@henryiii @galapaegos 

I've just fixed D2PPP.cpp code.

you can generate and fit a toy MC doing:

`
./D2PPP gen
./D2PPP fit
` 
This is the expected result 

pdf

**Comment by henryiii** [comment]
I could be wrong, but don't you need to do:
```diff
-    dtoppp.resonances.push_back(rho_12);
-    dtoppp.resonances.push_back(omega_12);
-    dtoppp.resonances.push_back(f2_12);
-    dtoppp.resonances.push_back(sigma_12);
-    dtoppp.resonances.push_back(f0_980_12);
-    dtoppp.resonances.push_back(f0_1500_12);
-    dtoppp.resonances.push_back(nonr);
-    //dtoppp.resonances.push_back(swave_12);
+    //dtoppp.resonances.push_back(rho_12);
+    //dtoppp.resonances.push_back(omega_12);
+    //dtoppp.resonances.push_back(f2_12);
+    //dtoppp.resonances.push_back(sigma_12);
+    //dtoppp.resonances.push_back(f0_12);
+    //dtoppp.resonances.push_back(nonr);
+    dtoppp.resonances.push_back(swave_12);
```
to test it and get that result?

**Comment by henryiii** [comment]
I've make a fork with changes to make it easier to test: https://github.com/henryiii/goofit_charm, PR here: JuanBSLeite/goofit_charm#1.

**Comment by galapaegos** [comment]
The images are very similar, but smooth as compared to the attached image.  The Spline constructor now calculates the derivatives and copies them to the internal buffer.

**Pull request merged**
