### PR TITLE
WIP: Martha fix cpv

### PR DESCRIPTION
**Pull request by marthaisabelhilton**
- Add CP-violation to Amp3Body_TD
- CPV formalism is in terms of the variables delta x and delta y which define the mixing parameters differently for D0 and D0bar.
- This compiles with cmake .. -DGOOFIT_DEVICE=OMP -DGOOFIT_EXAMPLES=OFF This needs work to work with the examples since in pipipi0 there is no CPV so throws an error.
- Add charm tag observable to Amp3Body_TD
- Add functions to Amp3Body_TD and python bindings (setD0Fraction, getD0Fraction)
- Add getFractions() function which prints the fit fractions and interference fit fractions of the resonances in the amplitude model.

### CODE REVIEW

**Comment by marthaisabelhilton** [comment]
Hello @henryiii @danielsibemol I think the checks are failing because of the submodules? Please can you check?

**Comment by henryiii** [comment]
Eigen was accidentally deleted this weekend (!), so that's a bit of a mess right now. Should come back online soon, they are working with GitLab to get it restored.

**Comment by marthaisabelhilton** [comment]
Ok thanks @henryiii so now the checks are failing as expected because the pipipi0 example doesn't work. So we need to either:
- Change the pipipi0 example to include CPV or
- make deltax and deltay optional parameters (I'm not sure how to do this)
Can someone comment on what we think is the best solution? @danielsibemol @FlorianReiss

**Comment by FlorianReiss** [comment]
> Ok thanks @henryiii so now the checks are failing as expected because the pipipi0 example doesn't work. So we need to either:
> 
>     * Change the pipipi0 example to include CPV or
> 
>     * make deltax and deltay optional parameters (I'm not sure how to do this)
> 
> 
> Can someone comment on what we think is the best solution? @danielsibemol @FlorianReiss

to me the quickest solution seems to be to include CPV in the example. Maybe setting it constant to zero to recover the previous behaviour of the test

**Comment by marthaisabelhilton** [comment]
Hi @danielsibemol @henryiii the tests are failing with a segmentation fault in the pipipi0 test please can you have a look? It seems to be failing when reading the data which shouldn't be affected by the changes on this MR?

**Comment by marthaisabelhilton** [comment]
Okay @danielsibemol @FlorianReiss this has been fixed now although I'm not sure it's a great solution. I have made the mistag and charmtag variables compulsory - not optional and changed the pipipi0 example to include these variables, set to zero.

**Comment by FlorianReiss** [comment]
> Okay @danielsibemol @FlorianReiss this has been fixed now although I'm not sure it's a great solution. I have made the mistag and charmtag variables compulsory - not optional and changed the pipipi0 example to include these variables, set to zero.

to me that seems like a pragmatic solution for the moment

**Comment by henryiii** [comment]
This still has "WIP" in the title? Is it ready for review?

**Pull request merged**
