### PR TITLE
MPI ready GooFit with Application Object

### PR DESCRIPTION
**Pull request by henryiii**
This MR adds an application object to GooFit. These is based on my [CLI11](https://github.com/henryiii/CLI11) library, and syntax for it in GooFit is based on ROOT's TApplication object:

~~~cpp
#include "goofit/Application.h"
GooFit::Application app("description", argc, argv);

// Add options
int value;
app.add_option("-v,--value", value, "Description of value")->required();

// Parse
try{
    app.run();
} catch(GooFit::ParseError &e) {
    return app.exit(e);
};
~~~

FindMPI and MPI setup/teardown are included. This also adds default command line arguments:

~~~
$ ./examples/addition/addition -h
Addition example
Usage: ./examples/addition/addition [OPTIONS...]

Options:
  -h,--help                   Print this help message and exit
  --gpu-dev INT=0             GPU device to use
  --show-gpus                 Show the available GPU devices and exit
  --goofit-details            Output system and threading details
~~~

To see a full-scale usage of this, look at the pipipi0 example. The syntax for calling that one has changed, please see the help. All other examples were directly converted. Two examples (multiply and convolution) were also cleaned up to remove memory leakage.

Comments and suggestions on both this and the CLI11 library are appreciated. Once GooFit hits version 2.0, I'll also version CLI11 to 1.0. This PR address #33.

### CODE REVIEW

**Comment by henryiii** [comment]
@galapaegos, please see if this fills your requirements for MPI setup/teardown.
@hassec, please check the reworked examples
Note that zachFit command line has changed

**Comment by galapaegos** [comment]
@henryiii, Thanks for this MR.  I think this is exactly what we need for the MPI init/cleanup.

**Comment by henryiii** [comment]
Ready for review, this is becoming too important to live outside of master.

**Comment by henryiii** [comment]
Sorry about the flags, I don't have any real MPI code in the branch, so didn't catch that.

Do you mean the `MPI_Init` call, or the first MPI calls?

**Comment by galapaegos** [comment]
No worries!

The flag being set '-DGOOFIT_MPI' is correct.  MPI_CXX_COMPILE_FLAGS is not being included when the compilation actually happens, I think that is the issue.  When I turned on the verbosity to show the compilation flags, I did not see the '-DGOOFIT_MPI' flag being passed.

**Comment by henryiii** [comment]
I think `MPI_CXX_COMPILE_FLAGS` was breaking the add_def command,  so the final part wasn't being included. Did you check the new PR to see if that method fixes it?

**Comment by henryiii** [comment]
I believe you've added CountVariable; could you make a PR with at least that portion so I can start moving to using it? Even if it's just something like:
```cpp
class CountVariable : public Variable {
    using Variable::Variable;
};
```

**Pull request merged**
